"""A stable launcher for the bundled MCP server.

The MCP server ships inside the app (``OpenProxy-server --mcp``), so there is
nothing for the user to install. But an agent's config stores a command path
*once*, and the binary's real location moves: every update swaps the bundle,
users drag apps between folders, and a Linux AppImage mounts at a random path
on every launch.

So the backend writes a tiny shim to ``~/.openproxy/bin/openproxy-mcp`` on
every startup, pointing at wherever the current build lives. Agents register
the shim; the shim never moves. Rewriting it is what makes "install once, keep
updating" hold.
"""

import os
import sys
import time
import stat

from server.constants import OPENPROXY_DATA_DIR, APP_VERSION

MCP_BIN_DIR = os.path.join(OPENPROXY_DATA_DIR, "bin")
SHIM_NAME = "openproxy-mcp.cmd" if sys.platform == "win32" else "openproxy-mcp"
SHIM_PATH = os.path.join(MCP_BIN_DIR, SHIM_NAME)
MCP_RUNTIME_DIR = os.path.join(OPENPROXY_DATA_DIR, "mcp-runtime")


def _repo_root() -> str:
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def mcp_target() -> tuple[list[str], str]:
    """The command the shim should run, and which layout it was derived from.

    * ``appimage``: the AppImage's squashfs mount is unmounted when the app
      exits and remounted somewhere else next launch, so the shim can't point
      into it. The target is the AppImage file itself; see ``_render_appimage``
      for how the shim gets from there to the backend binary.
    * ``frozen``: the PyInstaller backend binary, stable for .app / NSIS / deb.
    * ``dev``: the repo venv's interpreter running main.py.
    """
    frozen = bool(getattr(sys, "frozen", False))
    if frozen and sys.platform.startswith("linux") and os.environ.get("APPIMAGE"):
        return [os.environ["APPIMAGE"]], "appimage"
    if frozen:
        return [os.path.abspath(sys.executable), "--mcp"], "frozen"
    return [os.path.abspath(sys.executable), os.path.join(_repo_root(), "main.py"), "--mcp"], "dev"


def _render(target: list[str], layout: str) -> str:
    stamp = time.strftime("%Y-%m-%d %H:%M:%S")
    if sys.platform == "win32":
        quoted = " ".join(f'"{p}"' for p in target)
        return (
            "@echo off\r\n"
            f"rem Generated by OpenProxy {APP_VERSION} ({layout}) on {stamp}.\r\n"
            "rem Rewritten every time OpenProxy starts so it always runs the installed\r\n"
            "rem build. Register THIS file with your MCP client, not the path below.\r\n"
            f"{quoted} %*\r\n"
        )
    header = (
        "#!/bin/sh\n"
        f"# Generated by OpenProxy {APP_VERSION} ({layout}) on {stamp}.\n"
        "# Rewritten every time OpenProxy starts so it always runs the installed\n"
        "# build. Register THIS file with your MCP client, not the path below.\n"
    )
    if layout == "appimage":
        return header + _render_appimage(target[0])
    return header + f"exec {' '.join(_sh_quote(p) for p in target)} \"$@\"\n"


def _sh_quote(p: str) -> str:
    return "'" + p.replace("'", "'\\''") + "'"


def _render_appimage(appimage: str) -> str:
    """Shim body that runs the backend unpacked from the AppImage.

    Running the AppImage itself needs a FUSE mount, which fails outright on
    distros whose fusermount is fusermount3 (Ubuntu 26.04: "Cannot mount
    AppImage"). APPIMAGE_EXTRACT_AND_RUN isn't an out either: it lists every
    extracted file on stdout, which is the MCP stream. ``--appimage-extract``
    needs no FUSE, so unpack just the backend, once per AppImage build (keyed
    on mtime and size, so an update gets a fresh copy), and run it directly.
    """
    return (
        f"APPIMAGE={_sh_quote(appimage)}\n"
        f"CACHE={_sh_quote(MCP_RUNTIME_DIR)}\n"
        'KEY=$(stat -c %Y-%s "$APPIMAGE") || exit 1\n'
        'BIN="$CACHE/$KEY/resources/backend/OpenProxy-server/OpenProxy-server"\n'
        'if [ ! -x "$BIN" ]; then\n'
        '  mkdir -p "$CACHE" && TMP=$(mktemp -d "$CACHE/.extract.XXXXXX") || exit 1\n'
        "  (cd \"$TMP\" && \"$APPIMAGE\" --appimage-extract 'resources/backend/*' >/dev/null 2>&1)\n"
        '  if [ -x "$TMP/squashfs-root/resources/backend/OpenProxy-server/OpenProxy-server" ]; then\n'
        "    # Older builds' copies go; their servers were stopped by the update.\n"
        '    find "$CACHE" -mindepth 1 -maxdepth 1 ! -name "$KEY" ! -name ".extract.*" -exec rm -rf {} +\n'
        '    mv "$TMP/squashfs-root" "$CACHE/$KEY" 2>/dev/null  # loses harmlessly to a concurrent launch\n'
        "  fi\n"
        '  rm -rf "$TMP"\n'
        '  [ -x "$BIN" ] || { echo "openproxy-mcp: could not unpack the backend from $APPIMAGE" >&2; exit 1; }\n'
        "fi\n"
        'exec "$BIN" --mcp "$@"\n'
    )


def ensure_mcp_shim() -> str | None:
    """Write (or refresh) the shim. Returns its path, or None if that failed.

    Failure is non-fatal: the proxy works without the shim, the user just has
    to register the binary's path by hand. The UI falls back to saying so.
    """
    target, layout = mcp_target()
    content = _render(target, layout)
    try:
        os.makedirs(MCP_BIN_DIR, exist_ok=True)
        # Skip the write when nothing but the timestamp would change, so a
        # tool watching the file (or the user reading it) sees real changes.
        if os.path.isfile(SHIM_PATH):
            with open(SHIM_PATH, "r", encoding="utf-8", newline="") as f:
                existing = f.read()
            if _strip_stamp(existing) == _strip_stamp(content):
                return SHIM_PATH
        tmp = SHIM_PATH + ".tmp"
        with open(tmp, "w", encoding="utf-8", newline="") as f:
            f.write(content)
        if sys.platform != "win32":
            os.chmod(tmp, stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
        os.replace(tmp, SHIM_PATH)
        print(f"[MCP] Shim written: {SHIM_PATH} -> {' '.join(target)} ({layout})", flush=True)
        return SHIM_PATH
    except Exception as e:
        print(f"[MCP] Could not write shim at {SHIM_PATH}: {e}", flush=True)
        return None


def _strip_stamp(text: str) -> str:
    return "\n".join(
        line for line in text.replace("\r\n", "\n").split("\n")
        if " on 20" not in line  # the generated-on line
    )


def run_mcp_server() -> None:
    """Entry point for ``OpenProxy-server --mcp`` / ``python main.py --mcp``.

    Runs the MCP server over stdio in place of the proxy. Kept import-light so
    nothing here touches stdout before the MCP transport owns it.
    """
    if not getattr(sys, "frozen", False):
        # In a checkout the package lives beside the app, not in site-packages.
        sys.path.insert(0, os.path.join(_repo_root(), "mcp-server"))
    from openproxy_mcp.server import main
    main()
